[package]
name = "md5sumsum"
version = "0.1.0"
authors = ["Kamel Malki"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
jwalk = "0.5.1"